apiVersion: v1
kind: Pod
metadata:
  name: order-qmgr-prd-pod
spec:
  containers:
    - name: order-qmgr
      image: nginx:stable
      env:
        - name: ENV
          value: "prd"
        - name: APP
          value: "order-qmgr"
