apiVersion: v1
kind: Pod
metadata:
  name: order-owr-qmgr-dr-pod
spec:
  containers:
    - name: order-owr-qmgr
      image: nginx:stable
      env:
        - name: ENV
          value: "dr"
        - name: APP
          value: "order-owr-qmgr"
