apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: order-owr-qmgr-dr-route
spec:
  to:
    kind: Service
    name: order-owr-qmgr-dr-svc
  port:
    targetPort: http
  tls:
    termination: edge
